<?php

namespace Database\Factories;

use App\Enums\MemberGender;
use App\Models\Member;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Member>
 */
class MemberFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $gender = fake()->randomElement(MemberGender::cases())->value;

        return [
            'name' => fake()->name($gender),
            'code' => '', // Generated by the model
            'gender' => $gender,
            'birth_date' => fake()->date(),
            'photo' => null, # rand(1, 10) <= 8 ? $this->photoPath($gender) : null,
        ];
    }
}
